#!/usr/bin/env python3
"""Compile the checked-in GMD references and original courses to sorted C data."""
import base64
import collections
import gzip
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
NAMES = ['StereoMadness', 'BackOnTrack', 'Polargeist', 'DryOut']
TITLES = ['STEREO MADNESS', 'BACK ON TRACK', 'POLARGEIST', 'DRY OUT']
def rgb(r,g,b): return ((int(r)>>3)<<11)|((int(g)>>2)<<5)|(int(b)>>3)
def obj(x,y,id=8,rot=0,color=0,duration=0): return [round(x),round(y),id,rot,0,color,duration]

def decode(path):
    nodes = list(ET.parse(path).getroot()[0])
    props = {nodes[i].text:nodes[i+1].text for i in range(0,len(nodes),2)}
    encoded=props['k4']
    raw=gzip.decompress(base64.urlsafe_b64decode(encoded+'='*(-len(encoded)%4))).decode()
    entries=[]
    for part in raw.split(';'):
        items=part.split(',')
        entries.append(dict(zip(items[::2],items[1::2])))
    colors={}
    for channel in entries[0].get('kS38','').split('|'):
        items=channel.split('_'); c=dict(zip(items[::2],items[1::2]))
        if '6' in c: colors[c['6']]=rgb(c.get('1',0),c.get('2',0),c.get('3',0))
    result=[]
    for o in entries[1:]:
        if '1' not in o: continue
        id=int(o['1']); rot=round(float(o.get('6',0))/90)%4
        color=rgb(o.get('7',0),o.get('8',0),o.get('9',0)) if id in (29,30) else 0
        a=obj(float(o.get('2',0)),float(o.get('3',0)),id,rot,color,round(float(o.get('10',0))*240) if id in (29,30) else 0)
        a[4]=(int(o.get('4',0))&1)|((int(o.get('5',0))&1)<<1)
        result.append(a)
    return result,colors.get('1000',0x2199),colors.get('1001',0x1019)

def originals():
    # Each phrase has a readable approach and recovery. Repeated motifs develop
    # over the course; portal corridors reserve room to learn the new mode.
    courses=[]
    a=[]
    for x,n in [(540,1),(900,1),(1320,2),(1740,1),(2160,2),(2580,3),(3120,1),(3540,2)]:
        a += [obj(x+j*30,15) for j in range(n)]
    for x in [4140,4740,5340]:
        a += [obj(x,2,35)]+[obj(x+60+j*30,15) for j in range(5)]
    a += [obj(6000,165,13),obj(7800,149,12)]
    for x in range(6330,7620,360):
        a += [obj(x,15,1),obj(x,285,1),obj(x,255,8,2)]
    for x in [8250,8640,9060]: a += [obj(x,15),obj(x+30,15)]
    a += [obj(2850,105,1329),obj(6900,150,1329),obj(9180,105,1329)]
    courses.append(('NEON CIRCUIT','ORIGINAL / RHYTHM',a,9700,0x249b,0x0152,2,128))
    a=[]
    for x in [540,1050,1560]: a += [obj(x,15),obj(x+30,15)]
    for x in [2190,2790,3390]:
        a += [obj(x,2,35)] + [obj(x+60+j*30,15) for j in range(4)] + [obj(x+180,120,1329)]
    a += [obj(4140,165,13),obj(7470,149,12)]
    for k,x in enumerate(range(4500,7200,330)):
        a += [obj(x,15,1),obj(x,285,1)]
        a += [obj(x,45 if k%2==0 else 255,8,0 if k%2==0 else 2)]
    for x in [7980,8430,8880,9330]: a += [obj(x,15),obj(x+30,15),obj(x+60,15)]
    courses.append(('SKYLINE','ORIGINAL / FLIGHT',a,9900,0x92b8,0x4832,3,140))
    a=[]
    for x in [540,990,1440,1890]: a += [obj(x,15),obj(x+30,15)]
    a += [obj(2550,100,11)]
    for x in range(2490,5191,30): a += [obj(x,285,1)]
    for x in [2940,3420,3900,4380]: a += [obj(x,255,8,2),obj(x+30,255,8,2)]
    a += [obj(4860,225,10)]
    for x in [5550,6060,6570]: a += [obj(x,2,35)]+[obj(x+60+j*30,15) for j in range(5)]
    a += [obj(7290,165,13),obj(9270,149,12)]
    for x in range(7650,9090,360): a += [obj(x,15,8),obj(x,285,8,2)]
    for x in [9690,10110,10530]: a += [obj(x,15),obj(x+30,15)]
    a += [obj(1650,100,1329),obj(4050,200,1329),obj(8430,150,1329)]
    courses.append(('AFTERGLOW','ORIGINAL / GRAVITY',a,11100,0x04b3,0x0250,4,132))
    for _,_,a,ln,bg,gr,_,_ in courses:
        for x,c in [(ln//3,0x7918),(2*ln//3,bg)]: a.append(obj(x,0,29,color=c,duration=480))
    return courses

def main():
    courses=[]; manifest=[]
    for i,name in enumerate(NAMES):
        path=ROOT/'levels/reference'/f'{name}.gmd'
        a,bg,gr=decode(path)
        # A finish runway follows the original final object.
        length=max(o[0] for o in a)+240
        courses.append((TITLES[i],'ROBTop / ORIGINAL LAYOUT',a,length,bg,gr,i+1,[160,130,165,140][i]))
        manifest.append({'name':TITLES[i],'sha256':hashlib.sha256(path.read_bytes()).hexdigest(),'objects':len(a),'last_object_x':length-240,'object_ids':dict(collections.Counter(str(o[2]) for o in a))})
    courses+=originals()
    output=['/* Generated by tools/levels.py. Do not edit. */','#include "game.h"']
    for i,(_,_,a,*_) in enumerate(courses):
        a.sort(key=lambda o:o[0])
        assert len(a)<=4096 and all(0<=o[0]<=32000 and -300<=o[1]<=1500 for o in a)
        output.append(f'static const Object objects_{i}[] = {{')
        output += ['  {'+','.join(map(str,o))+'},' for o in a]
        output.append('};')
    output.append('const Level nd_levels[ND_BUILTINS] = {')
    for i,(name,credit,a,length,bg,gr,diff,bpm) in enumerate(courses):
        output.append(f'  {{"{name}","{credit}",objects_{i},{len(a)},{length},{bg},{gr},{diff},{bpm}}},')
    output.append('};\n')
    (ROOT/'src/levels.c').write_text('\n'.join(output))
    (ROOT/'levels/manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print('Compiled',sum(len(c[2]) for c in courses),'objects across',len(courses),'levels')
if __name__=='__main__': main()
