/* Generated by tools/levels.py. Do not edit. */
#ifndef NUMDASH_OBJDEFS_H
#define NUMDASH_OBJDEFS_H
#include <stdint.h>
enum {
  OT_NONE = 0,
  OT_BLOCK = 1,
  OT_GRID_T = 2,
  OT_GRID_TL = 3,
  OT_GRID_C = 4,
  OT_GRID_LTR = 5,
  OT_GRID_LR = 6,
  OT_GRID_DECO = 7,
  OT_DIAG_DECO = 8,
  OT_PLANK = 9,
  OT_SLAB0 = 10,
  OT_SLAB1 = 11,
  OT_SLAB2 = 12,
  OT_SLAB3 = 13,
  OT_SPIKE = 14,
  OT_SPIKE_SMALL = 15,
  OT_SPIKE_MED = 16,
  OT_PIT = 17,
  OT_ROD1 = 18,
  OT_ROD2 = 19,
  OT_ROD3 = 20,
  OT_DSPIKES1 = 21,
  OT_DSPIKES2 = 22,
  OT_DSPIKES3 = 23,
  OT_DSPIKES4 = 24,
  OT_CHAIN = 25,
  OT_CHAIN_SHORT = 26,
  OT_STAR = 27,
  OT_PAD_Y = 28,
  OT_PAD_B = 29,
  OT_PAD_P = 30,
  OT_ORB_Y = 31,
  OT_ORB_P = 32,
  OT_ORB_B = 33,
  OT_GRAV_N = 34,
  OT_GRAV_F = 35,
  OT_PORTAL_CUBE = 36,
  OT_PORTAL_SHIP = 37,
  OT_COIN = 38,
  OT_COUNT = 39
};
enum { HIT_NONE, HIT_SOLID, HIT_HAZARD, HIT_SPECIAL };
enum { SP_NONE, SP_PAD_Y, SP_PAD_P, SP_PAD_B, SP_ORB_Y, SP_ORB_P, SP_ORB_B, SP_GRAV_N, SP_GRAV_F, SP_PORTAL_CUBE, SP_PORTAL_SHIP, SP_COIN };
enum { CT_OBJ, CT_BLACK, CT_WHITE, CT_P1ADD, CT_P2ADD, CT_GLOW, CT_GLOW_Y, CT_GLOW_B, CT_GLOW_P };
enum { LAYER_DECO_BACK, LAYER_RODS, LAYER_ROD_BALLS, LAYER_DETAIL, LAYER_SPECIAL_GLOW, LAYER_SPECIAL, LAYER_PORTAL_BACK, LAYER_BLOCK_GLOW, LAYER_PLAYER, LAYER_COIN, LAYER_PORTAL_FRONT, LAYER_FILL, LAYER_BLOCK, LAYER_COUNT };
enum { PF_PULSE = 1, PF_RANDOM3 = 2, PF_COIN = 4, PF_ANIM = 8 };
enum { EV_COLOR = 1, EV_FADE = 2, EV_TRAIL = 3 };
typedef struct { int16_t sprite; int8_t dx4, dy4; uint8_t layer, ctype, flags; } ObjPart;
typedef struct { uint16_t gd_id; uint8_t hit, special; uint16_t w10, h10; int8_t editor_dy; uint8_t nparts; ObjPart parts[2]; } ObjDef;
extern const ObjDef objdefs[OT_COUNT];
#define EDITOR_TYPES 28
extern const uint8_t editor_types[EDITOR_TYPES];
#endif
